#+TITLE: Quests


* Explore Vault of Embers
* Explore City of Furnace.
* Explore Cloud City
* Retrieve Tokens of Power
* Explore Omega Region
* The elven rangers have discovered some dark elf activity
    This is what I've heard about The elven rangers have discovered some dark elf
activity: The elven rangers have discovered some dark elf activity was created by Moraq. Recently
it has been reported by the elven rangers that the dark elf activity around the forest of Kloernien
has grown excessively. The new Farseer, Zarhenol has ordered guard patrols to investigate this
menace, and indeed they found a dark elf hiding in a cave near the city walls
* Explore the Nests
* Explore Planitia Serpentium
* Explore Vault of Winds
* Noellanie's revenge
    Ereldon tells you 'This is what I've heard about Noellanie's revenge: Noellanie's revenge was
created by Tumi. On behalf of Noellanie, the elven leathercrafter who lost his foot and sight to
black alligator, slay the black alligator and bring back its hide to him so he can have his revenge.
'.
* Explore Planitia Ignis
* Explore City of Myth.
* Explore Fortress of Void
* Explore Gloom Cistern
* Explore Chasma Tetria
* Explore Central Basin
* Rescue the maiden
    Rescue the maiden was created
by Taabbio. A young daughter of a nobleman got bored with her luxurious life in her father's
castle, and ran away.  However, she was caught in a tremendous storm, and had to seek shelter.
Luckily she happened to be close to mansion owned by the Swaizzones, Count Yirica and his wife
Countess Azadril.  She approached the mansion and was heartily welcomed and shown to a nice
guestroom.  Unluckily, the Swaizzones really weren't that friendly after all, for they locked the
girl up in the guestroom, for some mysterious purposes of their own. Very soon after his girl was
gone, the noble got worried about her, and went looking for her.  He followed her trail to the
mansion, but doesn't have the guts to enter the mansion himself.  He's waiting for some adventurers
who'd be brave enough to go rescue his daughter and bring her back to him.  He's sure that the girl
would follow any adventurer who'd go to her and ask her to.
* Save the Avian community
* Explore Planitia Scycia
* Explore Bleak River
* Explore Terra Gloria
* Millanien the beautiful elf maiden is in trouble
    Millanien the beautiful elf maiden is in trouble was created by Moraq. Silvans, the young
apprentice Farseer in the forest of Kloernien has been having troubles with his love, Millanien.
The beautiful elf maiden is being forced to be the mistress' of a powerful elven councelor, even
though she does not want it. Silvans is desperate to help her and would gladly accept any help with
it.
* Macca the Head Smith has lost something
Macca the Head Smith has lost something was created by Echcua. Macca the Head Smith has lost something and is
desperately trying to find it '.
* Solael needs you to kill evil troll leader who is harming her forest
    This is what I've heard about Solael needs you to kill evil troll leader who is
harming her forest: Solael needs you to kill evil troll leader who is harming her forest was
created by Belannaer. Solael has announced that she will reward greatly the one who kills the evil
troll leader who is harming her forest with his evil deeds. The troll leader lives in the cave near
the forest with his family.
* Bring Arinbjorns cloak to Nharethe
    This is what I've heard about Bring arinbjorns cloak to nharethe: Bring
Arinbjorns cloak to Nharethe was created by Belannaer. Nharethe has been dreaming from Arinbjorns
cloak for ages.He wants it very much and will reward anyone who brings it to him.
* DONE Bring hand carved ring to Dezzo
    This is what I've heard about Bring hand carved ring to dezzo: Bring hand carved
ring to Dezzo was created by Belannaer. Dezzo, a halfling gardener living in the north in a small
halfling village called Highhill, has always dreamed about having the hand carved ring that
Leannan, the baker of the Highhill owns, he would be happy to get it.

    solve murnek first
* Explore Chasma Abysnoch
* Explore Temple of Magic
* Explore North Pole
* Explore Citadel of Pearls
* Explore Vault of Terror
* Help the gnome priest
Ereldon tells you 'This is what I've heard about Help the gnome priest: Help the gnome priest was
created by Kyrala. Help the gnome priest in solving the problems with the gate.He is at the portal
in a cave east of vaerlon.To solve this quest you should ask him about "mission" and solve the
problems on the other side of the portal. '.
* Explore the Catacombs
* Explore Azure Citadel
* Explore Skull Hills
* Explore Theta Region
* Help Oleith the historian
* Explore Gate Complex
* Explore City of Pacipis
* Explore City of Sol'daran
* Explore Door to Fortress
* Explore Citadel of Zephyrs
* Explore Mount Siretin
* Explore Vault of Desolation
* Explore Plasm Caenum
* Explore Ignis Porta
* Missing townspeople
This is what I've heard about Missing townspeople: Missing townspeople was
created by Ndarr. A small, yet busy town, called district #482 by the templars, is pestered by
cases of missing people. Who could find out what has happened to the lost people?
* Explore Chasma Leviara
* Explore City of Forge
* Explore Molten City
* Explore Crypt of Magic
* Aid Aesha in her quest
* DONE Slay wolf pack leader
    This is what I've heard about Slay wolf pack leader: Slay wolf pack leader was
created by Idles. Lurchak, the leader of an elf tribe, is having great difficulties. An evil wolf
pack is causing terror in his forest, and the elves have not been able to kill the wolves. They
need your help! To complete this quest you have to show a proof to Lurchak, that you have killed
the leader of the wolf pack.
* Explore Frozen Outpost
* Explore Temple of Albila

* Explore City of Spirit
* Find Eskara Valley
* Explore Maze of Despair
* Help the elf
* Carsadru's treasure chest
* Explore River of Lava
* Explore Corona Perpetua
* Master the dart throwing
* Explore Nautheas Basin
* Explore Stygian Sargasso
* Explore City of Alquarie
* Explore Zeta Region
* Explore White Monastery
* Live down the troubles in snow troll camp
* Explore Vault of Stone
* Explore City of Ash
* Fisher who wants to become a warrior
* Inform the Vaerlon Council of attack plans
Ereldon tells you 'This is what I've heard about Inform the vaerlon council of attack plans: Inform
the Vaerlon Council of attack plans was created by Cantil. There are rumours in the inns and
wayhouses of the Kingdom of Valkor that there is a new power rising somewhere near Graemor. Tales
are told of a massive fortress in the mountains and of the army being bred there. Rumour has it an
attack on Vaerlon is planned, and the Council is eager to get their hands on any information
pertaining to this rumoured attack. '.
* Explore Lost Mine
* Fishing
Ereldon tells you 'This is what I've heard about Fishing: Fishing was created by Idles. The fisher
isn't a real fisher before he has caught a big fish. To complete this quest, a fish bigger than
10kg's has to be shown to Astug, the old fisherman. '.
* Return the Glove
Ereldon tells you 'This is what I've heard about Return the glove: Return the Glove was created by
Favorit. Grrmzkh, the thieves hideout leader has a problem. He has lost his glove and is missing it
badly. He promised an award for the man who will find it and return it to him. '.
* Explore Crystal Grotto
* Explore Sunken Outpost
* Explore Tempris
* Explore Lands of Onyx
* Explore Vortex Vertigo
* Explore Silent Lands
* Explore Fountain of Life
* Explore the Underworld
* Explore Goblin Wilderness
* Explore Vault of Rust
* Explore Castle of Entropy
* The Dart Legend
Ereldon tells you 'This is what I've heard about The dart legend: The Dart Legend was created by
Idles. Throwing darts is often found an amusing sport in the inns and pubs while drinking some beer.
To become a living legend in throwing darts, you have to hit the bullseye three times a row, scoring
30 points! To do that is very hard and requires lots of training and patience. '.
* Explore Slate Fields
* Explore Dismal Shrine
* Explore City of Death
* Explore Death Swamp
* Help Gobble to finish a potion
Ereldon tells you 'This is what I've heard about Help gobble to finish a potion: Help Gobble to
finish a potion was created by Zaec. Help a goblin alchemist to find several ingredients for a
special potion. '.

nefankaz
* Provide assistance to those in need
    This is what I've heard about Provide assistance to those in need: Provide
assistance to those in need was created by Simius. Rumors speak of someone or something in the
Cenobium in need of assistance.
* Deollan's letter delivery problem
Ereldon tells you 'This is what I've heard about Deollan's letter delivery problem: Deollan's letter
delivery problem was created by Belannaer & Zeibutsu. Deollan, the wandering chronomancer merchant
is worried about his wife Lodran and his daughter Leodran. The problem is that he changes the place
where he is all the time and thus his wife can't send a letter to him. Deollan wants some
trustworthy adventurer to help him with this delivery problem and deliver his letter to his family
as he is too busy to go home right now. '.
* Help the Mayor
Ereldon tells you 'This is what I've heard about Help the mayor: Help the Mayor was created by
Favorit. Dagzom, the dwarven village mayor has a problem. His wife was stolen by orcs and prisoned
somewhere in the orcish camp.Help the mayor to rescue his wife and receive a reward. '.
* Save the nymph village
Ereldon tells you 'This is what I've heard about Save the nymph village: Save the nymph village was
created by Galiere. Save the village and the lovely nymphs inhabiting it by stopping a creature that
hunts them. Find Iloende the nymph near the Ranger Lord subguild and ask her about help. To complete
this quest you must stop whatever is the cause for the trouble. '.
* Resolve the mystery of the tower
Ereldon tells you 'This is what I've heard about Resolve the mystery of the tower: Resolve the
mystery of the tower was created by Ginjeet. A mysterious, abandoned tower was recently found in a
secluded valley far from everything.  Find out who or what used to inhabit it, and what happened to
them. '.
* Explore Volcanic Chasm
* Assist the Gypsy Magician
Magician says: Wow! You are willing to help me?! Great! I would really like
to become a fire breather, as I already told you. I would need a few items
in order to do this of course. I really appreciate you doing this for me.
For a list of what items I need, just ask me about items!

Magician says: I only need three items! The first, is a *fire rod*, for me to
breath fire through. The second is some *pure alcohol*. I'm sure some crazy
person must drink it. Only pure alcohol is flammable enough to create large
flames. The third and final, is some *instructions on fire breathing*, to
help me get started. That's it!
* Explore Mountain of Winds
* Solve the mystery of missing Mudtown inhabitants
Ereldon tells you 'This is what I've heard about Solve the mystery of missing mudtown inhabitants:
Solve the mystery of missing Mudtown inhabitants was created by Solar. There have been several
disappearances of citizens in Cenedoiss. The only thing in common with the disappeared people is
that they are all residents of the Mudtown district, and that they have disappeared when it is dark.
The citizens are afraid, and Cenedoiss authorities have promised a handsome reward for the one who
uncovers this mystery and has proof to back the story. '.
* Explore Sigmis
* Mushroom gathering
Ereldon tells you 'This is what I've heard about Mushroom gathering: Mushroom gathering was created
by Zeibutsu. Aiach is an old, blind woman, who loves creamed mushrooms. She can't gather mushrooms
anymore, so she needs someone to find her favourite mushrooms for her. She promises to reward an
experienced gatherer. '.
* Elements
(page 1):
                   -Foreword-

Praised be the elements, for they bring us life
and prosperity. This guiding knowledge will be given
to you, among the few other trustworthy followers,
who have been chosen to represent our devotion for
the elements. It shall be kept secret, so that this
sacred place will be safe from heretics like the
followers of The Red Wind. I have written these
words before my passing to make sure that you, as
a chosen champion, will receive this knowledge
directly from me and therefore know it to be true.


                  -The cavern-

This cavern was excavated and enchanted to serve as a
conduit to the elemental domains and for the sole
purpose of pleasing our beloved elemental gods and
goddesses by committing heroic acts before them, thus
showing our loyalty. You, among the other chosen ones,
will be sent to the near vicinity of the elemental
deities to impress them with your great wits and
prowess in battle. Show courage and fight till death,
so you don't bring us shame and misfortune. If you
survive the challenge and the elements find you worthy
enough for a mortal, they might even grant you with a
piece of their very essence. The gifts given by the
deities are worth far more than any of our lives, so
rejoice in the opportunity you have been given! It is
better to be favored by the elements in the Nether
Plane than to be shunned by them in this life.


                 -The domains-

During the phase of the chosen element, you will

(page 2):
gain access into its domain through the holy symbol,
which has been enchanted ages ago with the help of
high priests of every element.

As mentioned before, these domains are harsh places
and correct knowledge is required for survival.
The awaiting challenges are very hard and sometimes
even impossible for us mortals, depending on the mood
of the deities. Remember, if you aren't skilled enough
to overcome the obstacles they have placed, they will
still be pleased due to your ultimate sacrifice. With
the divine favor gained from sacrificing your brave
hearth, we will be able to pray for prosperity for
our community.


            -Attuning of the elements-

If you manage to return with one of the elements gifts,
you can be assured that the higher powers do not look
down on you, but see you as a possible mortal helper of
their reign because of your exceptional talent.
Furthermore, if we manage to retrieve each essence, they
will be used for even greater purpose.

To show our need for every elemental power and for the
peace between them, it has been a long tradition to unify
the essences as a gesture of peace towards the elements.

This must be done in two steps. First, the four concrete
essences must be combined in the chamber of the elements,
where the flow of elemental energies is in perfect
balance. This must be done before adding the neutral
essence of magic into the unified, concrete essences of
the four rivaling elements. Because of the nature of
magic, its essence simply cannot be gathered and brought
out of its domain, so it must be channeled. Therefore the

(page 3):
unified essences have to be taken into the domain of magic,
where the bonds between the opposing elements can be
strenghtened and the repelling completely diminished.

While the essences were originally combined as a gesture
of peace, we quickly noticed that they also combine into
powerful items that sizzle with magical properties. This
proves that the elements are truly powerful together, so
let's hope they continue to settle their age old quarrels



peacefully.

Feel free to spend your final night before the challenge
in the holy chamber of the elements for praying, so that
your spirit will be fully prepared for the most important
day of your life.

     -Jer'lean, the high priest of the elements
