#+TITLE: Quests


* Explore Vault of Embers
* Explore City of Furnace.
* Explore Cloud City
* Retrieve Tokens of Power
* Explore Omega Region
* The elven rangers have discovered some dark elf activity
    This is what I've heard about The elven rangers have discovered some dark elf
activity: The elven rangers have discovered some dark elf activity was created by Moraq. Recently
it has been reported by the elven rangers that the dark elf activity around the forest of Kloernien
has grown excessively. The new Farseer, Zarhenol has ordered guard patrols to investigate this
menace, and indeed they found a dark elf hiding in a cave near the city walls
* Explore the Nests
* Explore Planitia Serpentium
* Explore Vault of Winds
* Noellanie's revenge
* Explore Planitia Ignis
* Explore City of Myth.
* Explore Fortress of Void
* Explore Gloom Cistern
* Explore Chasma Tetria
* Explore Central Basin
* Rescue the maiden
* Save the Avian community
* Explore Planitia Scycia
* Explore Bleak River
* Explore Terra Gloria
* Millanien the beautiful elf maiden is in trouble
* Macca the Head Smith has lost something
* Solael needs you to kill evil troll leader who is harming her forest
    This is what I've heard about Solael needs you to kill evil troll leader who is
harming her forest: Solael needs you to kill evil troll leader who is harming her forest was
created by Belannaer. Solael has announced that she will reward greatly the one who kills the evil
troll leader who is harming her forest with his evil deeds. The troll leader lives in the cave near
the forest with his family.
* Bring Arinbjorns cloak to Nharethe
    This is what I've heard about Bring arinbjorns cloak to nharethe: Bring
Arinbjorns cloak to Nharethe was created by Belannaer. Nharethe has been dreaming from Arinbjorns
cloak for ages.He wants it very much and will reward anyone who brings it to him.
* Bring hand carved ring to Dezzo
    This is what I've heard about Bring hand carved ring to dezzo: Bring hand carved
ring to Dezzo was created by Belannaer. Dezzo, a halfling gardener living in the north in a small
halfling village called Highhill, has always dreamed about having the hand carved ring that
Leannan, the baker of the Highhill owns, he would be happy to get it.
* Explore Chasma Abysnoch
* Explore Temple of Magic
* Explore North Pole
* Explore Citadel of Pearls
* Explore Vault of Terror
* Help the gnome priest
* Explore the Catacombs
* Explore Azure Citadel
* Explore Skull Hills
* Explore Theta Region
* Help Oleith the historian
* Explore Gate Complex
* Explore City of Pacipis
* Explore City of Sol'daran
* Explore Door to Fortress
* Explore Citadel of Zephyrs
* Explore Mount Siretin
* Explore Vault of Desolation
* Explore Plasm Caenum
* Explore Ignis Porta
* Missing townspeople
This is what I've heard about Missing townspeople: Missing townspeople was
created by Ndarr. A small, yet busy town, called district #482 by the templars, is pestered by
cases of missing people. Who could find out what has happened to the lost people?
* Explore Chasma Leviara
* Explore City of Forge
* Explore Molten City
* Explore Crypt of Magic
* Aid Aesha in her quest
* TODO Slay wolf pack leader
    This is what I've heard about Slay wolf pack leader: Slay wolf pack leader was
created by Idles. Lurchak, the leader of an elf tribe, is having great difficulties. An evil wolf
pack is causing terror in his forest, and the elves have not been able to kill the wolves. They
need your help! To complete this quest you have to show a proof to Lurchak, that you have killed
the leader of the wolf pack.
* Explore Frozen Outpost
* Explore Temple of Albila

* Explore City of Spirit
* Find Eskara Valley
* Explore Maze of Despair
* Help the elf
* Carsadru's treasure chest
* Explore River of Lava
* Explore Corona Perpetua
* Master the dart throwing
* Explore Nautheas Basin
* Explore Stygian Sargasso
* Explore City of Alquarie
* Explore Zeta Region
* Explore White Monastery
* Live down the troubles in snow troll camp
* Explore Vault of Stone
* Explore City of Ash
* Fisher who wants to become a warrior
* Inform the Vaerlon Council of attack plans
* Explore Lost Mine
* Fishing
* Return the Glove
* Explore Crystal Grotto
* Explore Sunken Outpost
* Explore Tempris
* Explore Lands of Onyx
* Explore Vortex Vertigo
* Explore Silent Lands
* Explore Fountain of Life
* Explore the Underworld
* Explore Goblin Wilderness
* Explore Vault of Rust
* Explore Castle of Entropy
* The Dart Legend
* Explore Slate Fields
* Explore Dismal Shrine
* Explore City of Death
* Explore Death Swamp
* Help Gobble to finish a potion,
* Provide assistance to those in need
    This is what I've heard about Provide assistance to those in need: Provide
assistance to those in need was created by Simius. Rumors speak of someone or something in the
Cenobium in need of assistance.
* Deollan's letter delivery problem
* Help the Mayor
* Save the nymph village
* Resolve the mystery of the tower
* Explore Volcanic Chasm
* Assist the Gypsy Magician
* Explore Mountain of Winds
* Solve the mystery of missing Mudtown inhabitants
* Explore Sigmis
* Mushroom gathering
